/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "airconwithme adapter settings": {               "en": "Adapter settings for airconwithme",               "de": "Adaptereinstellungen für airconwithme",           "ru": "Настройки адаптера для airconwithme",             "pt": "Configurações do adaptador para airconwithme",    "nl": "Adapterinstellingen voor airconwithme",           "fr": "Paramètres d'adaptateur pour airconwithme",       "it": "Impostazioni dell'adattatore per airconwithme",   "es": "Ajustes del adaptador para airconwithme",         "pl": "Ustawienia adaptera dla airconwithme",            "zh-cn": "airconwithme的适配器设置"},
    "ipaddress": {                                   "en": "IP Address",                                      "de": "IP Adresse",                                      "ru": "Айпи адрес",                                      "pt": "Endereço de IP",                                  "nl": "IP adres",                                        "fr": "Adresse IP",                                      "it": "Indirizzo IP",                                    "es": "Dirección IP",                                    "pl": "Adres IP",                                        "zh-cn": "IP地址"},
    "password": {                                    "en": "Password Login Intesis (Default: admin)",         "de": "Password Login Intesis (Standard: admin)",        "ru": "Пароль для входа в Intesis (по умолчанию: admin)", "pt": "Login de senha Intesis (Padrão: admin)",          "nl": "Wachtwoord Login Intesis (Standaard: admin)",     "fr": "Mot de passe de connexion Intesis (par défaut: admin)", "it": "Password di accesso Intesis (impostazione predefinita: admin)", "es": "Contraseña Iniciar sesión Intesis (Predeterminado: admin)", "pl": "Hasło Login Intesis (Domyślnie: admin)",          "zh-cn": "密码登录名（默认值：admin）"},
    "username": {                                    "en": "Username Login Intesis (Default: admin)",         "de": "Benutzername Login Intesis (Standard: admin)",    "ru": "Имя пользователя для входа в Intesis (по умолчанию: admin)", "pt": "Login de nome de usuário Intesis (Padrão: admin)", "nl": "Gebruikersnaam Login Intesis (Standaard: admin)", "fr": "Nom d'utilisateur Login Intesis (par défaut: admin)", "it": "Nome utente Login Intesis (predefinito: admin)",  "es": "Nombre de usuario Iniciar sesión Intesis (predeterminado: admin)", "pl": "Nazwa użytkownika Login Intesis (Domyślnie: admin)", "zh-cn": "用户名登录名（默认值：admin）"},
    "IP Address of the Mitsubishi WLAN adapter": {   "en": "IP Address of the Mitsubishi WLAN adapter",       "de": "IP-Adresse des Mitsubishi WLAN-Adapters",         "ru": "IP-адрес адаптера WLAN Mitsubishi",               "pt": "Endereço IP do adaptador Mitsubishi WLAN",        "nl": "IP-adres van de Mitsubishi WLAN-adapter",         "fr": "Adresse IP de l'adaptateur WLAN Mitsubishi",      "it": "Indirizzo IP dell'adattatore WLAN Mitsubishi",    "es": "Dirección IP del adaptador WLAN Mitsubishi",      "pl": "Adres IP karty Mitsubishi WLAN",                  "zh-cn": "三菱WLAN适配器的IP地址"},
    "Username for login on adapter website (default:admin)": {"en": "Username for login on adapter website (default:admin)", "de": "Benutzername für die Anmeldung auf der Adapter-Website (Standard: admin)", "ru": "Имя пользователя для входа на сайт адаптера (по умолчанию: admin)", "pt": "Nome de usuário para login no site do adaptador (padrão: admin)", "nl": "Gebruikersnaam voor inloggen op adapterwebsite (standaard: admin)", "fr": "Nom d'utilisateur pour la connexion sur le site Web de l'adaptateur (par défaut: admin)", "it": "Nome utente per l'accesso sul sito Web dell'adattatore (predefinito: admin)", "es": "Nombre de usuario para iniciar sesión en el sitio web del adaptador (predeterminado: admin)", "pl": "Nazwa użytkownika do logowania na stronie adaptera (domyślnie: admin)", "zh-cn": "适配器网站上登录的用户名（默认：admin）"},
    "Password for login on adapter website (default:admin)": {"en": "Password for login on adapter website (default:admin)", "de": "Passwort für die Anmeldung auf der Adapter-Website (Standard: admin)", "ru": "Пароль для входа на сайт адаптера (по умолчанию: admin)", "pt": "Senha para login no site do adaptador (padrão: admin)", "nl": "Wachtwoord voor inloggen op adapterwebsite (standaard: admin)", "fr": "Mot de passe pour la connexion sur le site Web de l'adaptateur (par défaut: admin)", "it": "Password per l'accesso sul sito Web dell'adattatore (impostazione predefinita: admin)", "es": "Contraseña para iniciar sesión en el sitio web del adaptador (predeterminado: admin)", "pl": "Hasło do logowania na stronie adaptera (domyślnie: admin)", "zh-cn": "适配器网站登录密码（默认：admin）"},
};